### ISSUE TITLE
[Bug] Can't upload photos from Ipad (safari) after Cryptee update

### ISSUE THREAD

**Issue by MoralCoral** [cryptee/web-client#216] opened 2024-07-14 17:25 UTC
**Describe the bug**
Can't upload photos from Ipad (safari) after Cryptee update

**To Reproduce**
1. Enter Album
2. Click upload
3. Click "From photos"
4. Select files
5. Nothing happens

Alternative:
1. Open Album
2. Select files in Apples Photos app
3. Drag the files from the Photos app to Cryptee
4. Get the "Drop files here" promt from Cryptee
5. Wait 15min but nothing happens

**Expected behavior**
Photos will start uploading

**System Information (please complete the following information):**
 - Device: [iPad Pro 11in M1 512GB]
 - OS: [iPad OS 17.5.1]
 - Browser [Safari]
 - Browser Version [Latest]
 - Browser Extensions / Add-ons / Content/Ad-Blockers [None] 
 - Do you have any DNS-based content/ad-blockers? [No]
 - Are you on a managed network? [No]

**Additional context**
This has worked before and stopped working after the Cryptee update

**Comment by johnozbay** [comment] 2024-07-15 06:17
Hi there, thanks for reaching out with this. 
All our manual and automated tests seems to be working. (and we tested on the same exact device & OS version by the way) 
So chances are what you're dealing with is related to one of these : 

— Lockdown Mode. If you have it enabled, please try again after disabling it. [Here's why](https://crypt.ee/help?article=why-cant-i-use-cryptee-when-ios-lockdown-mode-is-enabled-on-my-iphone-or-ipad).

— iOS Safari privacy protections. Try "reduce privacy protections" them if Safari shows this banner. It seems to mess with browser's canvas, which affects thumbnail generation during uploads. ([more info here](https://crypt.ee/help?article=why-does-cryptee-photos-require-access-to-my-browsers-canvas))

— Failed app installation. There's always a non-zero chance that you had a network drop out or some unexpected issue during Cryptee's installation / last update. Try heading over to beta.crypt.ee, and uploading there. (currently both `beta` and `live` (crypt.ee) have the same exact version running. If your uploads work on beta.crypt.ee, then chances are you had an installation related issue, and we can look into what may have caused this, and offer guidance for you for a clean re-install. (as well as figure out what causes this and fix it on our end of course)

— Your photos. On iOS, there are a bunch of edge cases that could cause this. 
1) iOS "Photos" app tries to convert all photos to JPG when uploading inside Safari. i.e. if you have a DNG or TIFF photo inside your photos app, Photos app pretty much grinds to a halt while trying to convert them (without any indication to the user), and after an absurd amount of time keeping the user waiting without any indication it will upload JPG). To combat this most professional photographers who shoot RAW photos use the Files app instead. Because if you select your photos using the Files app (by clicking on "Choose Files" instead of "Photo Library") then iOS doesn't try to convert the photos and you can upload RAW photos. It's absurd. 

2) iOS and Safari have a pretty bad file manager, and it kinda fails miserably with large number of selections no matter how good the CPU on the iPad is. For example, open Files app, try copy pasting 1,000 photos from an SD card to another folder on your iPad. You'll notice the app will either crash or take forever without an indication. Same with selections in Safari. If you happen to be choosing lots of photos to upload to Cryptee, iOS may be grinding to a halt. 

3) Available memory. If you're using lots of background apps etc + on battery saver in Safari, iOS reduces the available memory to all apps (incl Safari, and Safari reduces the available memory to all tabs, incl Cryptee) which can cause it to grind to a halt, depending on how many apps you have running. 

4) Your specific photos themselves may be potentially buggy. Due to the fact that iOS tries to convert photos during upload, sometimes it messes up photos' metadata. So in order for us to eliminate this may be the problem, we would need to test with one of your photos. So if you'd like, and if it's okay for you to share, can you send one photo we can reproduce this issue with to `support {at} crypt [dot] ee`? That way we can make sure things are fixed. 

---

We'll be looking forward to hearing from you to be able to assist you further. 
Best,
J

**Comment by MoralCoral** [comment] 2024-07-15 17:42
Hi,
Thank you for the swift response. Ive gone through all of the above potential issues without avail. Even the beta channel test came out negative. I proceeded to save my photos from the Photos app to the files app and that worked. The issue I got then is that the heic "apples god forsaken file format" wont get converted to Jpeg during upload like it did if I used the Photos app. If i where to convert them myself I will loose the meta data so the photos would end up mixed or at the end of the album which is a bummer. The file types of the photos is a mix of Jpeg and Heic because some of them is from a friend who uses iPhone that had them airdropped to me.
The crazy thing is that it worked about a week ago without any issues.
Kind regards
MoralCoral

**Comment by johnozbay** [comment] 2024-12-12 20:00
Hi there! Our latest update ( 42a878604475e86ba7cca05079b4d2db6040ade2 ) *should* ~hopefully~ fix this bug in combination with iOS 18.2. We made some pretty hardcore changes to our upload pipeline. You can read more about this [here](https://blog.crypt.ee/cryptee-photos-supports-all-raw-photo-formats/
). + iOS 18.2 adds better handling for files and photos. 

That being said, my recommendation here would be to make sure you choose the correct format you wish to upload your photos in from the iOS file selector popup, by first pressing the setting icon in the bottom right corner : 

![IMG_7568](https://github.com/user-attachments/assets/2f1b650f-4a11-4924-94e9-c7cb217b6dd5)

Then choosing the "Most Compatible", so that the photos are converted to JPG. 

![IMG_7569](https://github.com/user-attachments/assets/93775394-a629-45c2-a093-64a8e5826eba)

I believe what happened is that Apple changed the default behavior, and stopped converting HEIC even in places where it should be converting it.

( funnily enough HEIC was / has been an issue with even iCloud.com itself. [[1](https://discussions.apple.com/thread/251323355?sortBy=rank)] [[2](https://www.reddit.com/r/applehelp/comments/kwwcmy/uploading_heic_photos_to_icloud/)] etc... I don't know if it's better now, but it has been an ongoing struggle for many to say the least. + not to mention the pain they caused to all web developers, since ... Safari is literally the only browser that supports it, making it effectively useless for 90% of the planet ) 

Anyhow, give the updates + this setting a try, and let me know how it goes! 
For now I'll close this bug — but if you continue to experience the issue, please shoot a comment and we'll dig deeper!

Thanks for your patience in the meantime ✌🏻

Best,

J

**Closed as completed by johnozbay** 2024-12-12 20:00 UTC
Labels: bug, help wanted
