### ISSUE TITLE
[Bug] Assorted markdown shortcut issues

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#77] opened 2020-06-23 19:25 UTC
## Describe the bug

Two small issues with markdown shortcuts that turn out to be very disruptive in practice. I'm so sick of accidentally forgetting to add an extra space after italics, and then having to backspace to add it, but then accidentally making the following text italic (because Cryptee continues the formatting at the cursor position), and then having to fiddle with text selection and formatting on a little touchscreen to get things formatted correctly 🤯 

1.  [desktop & ios] Italic markdown shortcut eats the trailing space.
2. [ios] Markdown bullet shortcut requires being triggered twice.

### To Reproduce
**1. Italic shortcut (desktop & ios)**
1. Type text and surround it with either `*...*` or `_..._`
2. Type a space after the closing to trigger the markdown shortcut
3. The cursor ends up directly adjacent to the italicized text

**2. Bullet shortcut (ios)**
1. Type `*` on a new line
2. Type space to attempt to trigger the markdown shortcut
3. Observe a space gets typed and no formatted bullet appears
4. Press backspace, then type space again
5. Observe the markdown shortcut gets triggered and a formatted bullet appears

### Expected behavior
1. Text italicized using the markdown shortcut should have a trailing space, just like what happens with bold text.
2. [ios] The markdown bullet shortcut should be triggered on the first space typed, just like on other platforms.

### Screenshots
![md_italicbold](https://user-images.githubusercontent.com/273696/85447412-6ed6ce00-b54a-11ea-9d35-348e2be74b72.gif)
_Italic shortcut behvaior on Firefox on macOS_

![md_bullets](https://user-images.githubusercontent.com/273696/85447724-cc6b1a80-b54a-11ea-866e-fbeab8c6db41.gif)
_Bullet shortcut behavior on iOS_

## System Information
**Desktop:**
 - Device: Macbook Pro
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox
 - Browser Version: 77.0.1
 - Browser Extensions / Add-ons / Content Blockers: All disabled for testing

**iOS:**
 - Device: iPhone 6s
 - OS: iOS 13.4.1
 - Browser: Safari PWA

**Comment by dhda** [comment] 2020-06-24 01:42
I also noticed that typing `*text*,<space>` doesn’t trigger the italics shortcut, while `**text**,<space>` does trigger the bold shortcut. I think the behavior of the bold shortcut is desirable and correct in this case, as well.

**Comment by nyhilum** [comment] 2020-08-14 12:30
I would like to add on to this bug as it relates to markdown issues.

When using markdown code ticks (``), it generates extraneous spaces in the front and in the back of the word you turned into code. Specifically, in the front of a word, it generates a single space, but at the end of the word, it adds two spaces. For example:
![image](https://user-images.githubusercontent.com/32823053/90248648-ba954d80-ddfe-11ea-87dd-59460670221a.png)

For context, the `.text` is at the beginning of a line, but the position of the word doesn't actually matter. I didn't highlight it, but you can see the extra space at the front of `.code` as well.

**Comment by johnozbay** [comment] 2020-08-18 06:10
Thank you so much for these both 🙏🏻
 
And apologies for the long silence! 
We're working on a major v3.0 for the entire service, – a complete re-factor & re-design – for the whole service, and it's been taking up a great deal amount of our time, but for a great cause I promise. 

We're going to get fixes out for these as quickly as possible. In the meantime, feel free to shoot more of these as you find them. [Markdown Specs](https://spec.commonmark.org/0.29/) are a beast to implement, so I'd be pleasantly surprised if the only few bugs are the ones we have here. 😅

Many thanks 🙏🏻

**Comment by johnozbay** [comment] 2021-06-30 13:14
Hey there! 

Apologies for the delay! 
I've got some good news! 

1) We've fixed the italic/bold markdown shortcut bugs and the `code` bug in the alpha version now and linked this issue to our internal issue/release tracker. Once the update with this fix is out (should be in a few days), this issue will be closed automatically, and you'll get a notification!

2) Regarding creating bullets on iOS with asterisk. We did some intense testing, and concluded that this is in fact an iOS bug that is _specific to iphones_ and one that somehow doesn't affect ipads, and there's nothing we can do to fix it, and I've got videos to prove it. 

# on iPad with Bluetooth Keyboard & on-screen keyboard it works as expected : 

https://user-images.githubusercontent.com/611338/123963149-da077b80-d9ba-11eb-8b99-e29573de7d59.mov

# on iPhone with Bluetooth Keyboard it works as expected : 

https://user-images.githubusercontent.com/611338/123963266-f4415980-d9ba-11eb-9084-d7a90b0d8f07.MP4

# on iPhone with software keyboard it doesn't work as expected : 

https://user-images.githubusercontent.com/611338/123963298-fe635800-d9ba-11eb-8c22-de755f8e7359.MP4

---

So I'm inclined to think this is in fact a bug specific to iPhone soft-keyboards (and not even iOS soft-keyboards in general, as you can see it somehow works on iPads) – so I don't know what more we can do about this, other than recommending you to use `-` instead of `*` for creating lists on iPhones 🤦🏻‍♂️  which somehow works. 

And funnily enough, our code takes both `-` and `*` all the same. So there's no reason why one should work and other shouldn't, unless iPhone's soft keyboard isn't sending the `spacebar` after the `*` for some reason. 

https://github.com/cryptee/web-client/blob/2d8a55170e42845960a1843c458abf672efc7355/source/js/quill-modules/keyboard-bindings-and-hotkeys.js#L226

https://github.com/cryptee/web-client/blob/2d8a55170e42845960a1843c458abf672efc7355/source/js/quill-modules/keyboard-bindings-and-hotkeys.js#L243-L246

– We've also tested this with keyboards other than US-EN, like Swedish / Finnish etc to see if it helps, but it doesn't. 

– Also tried turning off auto-capitalisation / auto-correct etc thinking perhaps that's what causes the bug, but none helped.

Somehow there's an asterisk + space related bug on iPhone keyboards. We're open to ideas, but until we can isolate what's causing this I don't think we can file it as a bug report with Apple either. So let me know if you discover what may be the cause. (Or if it's on us, let me know, we're open for ideas, and we'll happily fix it if we can) but otherwise, for now, looks like we've addressed all the issues in this thread, and the upcoming version will automatically close this issue! 

Many thanks for filing this, your patience and help with all this! ✌🏻

Best,

J

**Comment by johnozbay** [comment] 2021-07-11 05:38
Hi there, 

We've finally fixed these in the alpha version and linked this issue to our internal issue/release tracker.
Once the update with this fix is out (should be in a few days), this issue will be closed automatically, and you'll get a notification!

Thank you so much for your help and patience with these long-standing bugs! 🙏🏻

**Closed as completed** 2021-07-12 13:40 UTC
Labels: bug

**Comment by dhda** [comment] 2021-07-14 23:53
Thanks so much! That’s so bizarre about how iPhones do something inexplicable with asterisks 😳.

**Comment by johnozbay** [comment] 2021-07-22 18:34
You're very welcome! hahahah soft-keyboards have become strangely complicated nowadays. Pretty sure it's some regex / autocorrect / predictive typing anomaly of some sorts. i.e. iPads don't have swipe-typing, but iPhones do = leading me to think that the underlying predictive typing code for the keyboards must be different, and somehow produce this weird result 😅

**Comment by dhda** [comment] 2021-07-22 18:45
Well, I just tested this with the floating swipe keyboard on my iPad and it has the same bug as the iPhone! So that’s some confirmation for your theory.
