### ISSUE TITLE
Large files fail to upload on iOS

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#54] opened 2020-04-25 20:05 UTC
On iOS, attempting to upload a large file from the files browser into a Cryptee folder causes the app to fail and return to the “starting up” screen, requiring me to enter my encryption key again. Sometimes it also requires logging in again (but I haven’t been able to suss out under what circumstances). After entering my key again, the file is not present.

A 100kb file works, a 1mb file works, a 15mb file fails.

**To Reproduce**
1. Create a folder in Cryptee
2. Click on the “...” context menu for the folder 
3. Click “Upload a file to folder”
4. Click “browse”...
5. Select a largish device-local file
6. Let Cryptee try to upload and encrypted until it fails.

**Expected behavior**
The file encrypts, uploads, and becomes accessible in the folder.

**System Information**
 - Device: iPhone 6s
 - OS: iOS 13.2.3
 - Browser: PWA installed to my home screen

**Comment by dhda** [comment] 2020-04-25 20:07
While testing this I found that Cryptee seems to not be maintaining context in a number of ways. Sometimes switching away from the app and then returning will force me to log in again (I’d expect it to only need my encryption key). One time when it crashed on a large file it decided to change from a light theme to a dark theme. Not really sure what’s going on with all that and I don’t have enough of a repro right now to justify filing a new issue for it.

**Comment by johnozbay** [comment] 2020-04-25 20:41
Hi there! 👋🏻
Thanks for filing this. 

Allow me to address these one at a time. 
First. 
Can you confirm the size of the file you're trying to upload is indeed 15mb? 
(or by any chance is it larger?)

Due to on device encryption, encoding, (and thumbnail generation for images, and even occasionally compression) there is a maximum file-size limit of about 40 - 50mb. We even have a help article about this specific shortcoming of on-device encryption :  
https://crypt.ee/help?article=how-large-of-a-file-can-i-upload

To add insult to the injury here, encryption & encoding also increases file size a little bit. 
We have another article detailing this here : 
https://crypt.ee/help?article=why-are-my-files-larger-on-cryptee-than-on-my-device 

(And we're not the only ones. OpenPGPjs, the library Cryptee's using for encryption, is developed by ProtonMail, and they have exactly the same shortcomings. – linked in the articles. It's just a lot less noticeable there, due to being a mail provider attachment sizes are limited to 15mb or something similarly low) 

Secondly, not all filetypes are created equally. 
It's easier to serialize a plaintext file, vs a compressed image, vs a compressed video. For example, we have users who had success uploading 100mb plaintext files on powerful desktops, and users who max'ed out with 30mb zip files on weak-ish android tablets. 

In a way, this partially depends on the available memory, something which browsers don't provide an API to detect (since it could be abused for fingerprinting) – so based on our tests, most devices, running modern & popular browsers, still work up to 40mb, and start to fail around 50+ megabytes. 

So if you can confirm that the file you're trying to upload is indeed smaller than ~35 - 40mb (on disk size might be shown different on iOS, so I'm leaving enough room for error here) then:

- Depending on the filetype, if it's highly compressed (i.e. audio, image, or video), 
- If there are other apps open (i.e. Spotify playing in the background or mail downloading sth) 
- Your iPhone 6S's battery is older ([so apple's limiting memory usage](https://www.vox.com/2017/12/22/16807056/apple-slow-iphone-batteries)) 

there's a very-very slim, but real chance that 15mb might be maxing out your device's available memory, resulting in a crash.

And unfortunately there really isn't an easy way to prevent these until browsers allow for a way to detect available memory. 

---

As for app losing state / context – this has been an incredibly annoying and well known iOS bug since iOS 12. ([Here's a whole article talking about it](https://medium.com/@firt/iphone-11-ipados-and-ios-13-for-pwas-and-web-development-5d5d9071cc49))

> If the Web.app process restarts, it seems it’s not saving the state as in 12.2 anymore; all the PWAs in the background seem to start from scratch.

This got better in iOS 13, but it also started killing apps more aggressively to save battery in general, resulting in more lost states. So tying this to the earlier point – if your device's running on limited memory, your phone will start killing apps in the background. (so switching apps could result in Cryptee losing context.) I can confirm that on our test devices, we have older devices quit more frequently, and newer devices retain longer. 

We have test devices running iOS 13.4.5 beta right now, and this seems a lot better, and most likely fixed entirely if Apple doesn't change anything.

---

Overall, we're doing some re-factoring to make the app slimmer, so that it uses less and less memory to fight some of these issues. (in the last 3 months alone, we've reduced the app's size & memory footprint by 50%, so it's getting better) 

Hoping these make sense! 

I'll be looking forward to your confirmation regarding the first point – I don't want to eliminate the possibility that we may have made a mistake somewhere, but I know we haven't changed anything memory-critical in the uploader in a while, so my guess is it's the phone killing it. 

Thanks again for filing this! 
Best,
J

**Comment by dhda** [comment] 2020-04-25 21:08
Thanks for the quick reply! Yes, i confirmed, and the file is 15.4MB (15,413,051 bytes). It’s a .pptx PowerPoint presentation, which is a binary file format. I’m unclear as to why the type of bytes you’re reading and encrypting would make a difference—could you explain what you mean? You're compressing before encrypting?

Closing all the other apps running (as best I can from the app switcher, not sure how iOS implements this internally) on my phone doesn’t have an impact.

Also, this phone's battery was replaced (by an Apple Store) about 6 months ago.

**Comment by dhda** [comment] 2020-04-25 21:36
I'm experimenting with some binary test files generated from /dev/random.

5mb   ✅   (9.9mb upload size)
7.5mb ✅  (14.9mb upload size)
10mb  ❌  (fails just like the initial file i was testing with)

So it actually fails even lower than 15MB.

2x increase in file size is pretty rough performance. I hope the Streams API becomes fully supported across browsers soon!

**Comment by dhda** [comment] 2020-04-25 22:32
Ok, I figured out that I can clear my phone’s memory by holding the home button for 5 seconds from the power off screen. Neat trick. I tested the 10mb file again after clearing memory, and this time it worked (with a 20mb upload size)!

With freshly cleared memory, a 15mb file still fails.

That confirms for me that it is an issue with my device running out of memory.

**Comment by johnozbay** [comment] 2020-04-26 04:56
Hey @dhda! 

Thanks for the updates! 

I'm simultaneously both happy and sad to hear it's about your device. 
Happy that I was correct to assume it's likely the memory, but sad because I wish it was a bug with Cryptee, something I could fix & improve easily, vs a browser/OS/hardware issue I can't help fix. 

> I’m unclear as to why the type of bytes you’re reading and encrypting would make a difference—could you explain what you mean? You're compressing before encrypting?

From my first answer : 

> Due to on device encryption, encoding, (and thumbnail generation for images, and even occasionally compression)

To give you a bit more specifics here, when you drag & drop a file / upload, for cross-browser compatibility reasons we use the `readAsDataURL()` api of the browser to read the file. 

https://github.com/cryptee/web-client/blob/42137a87de5d3725986f74f9beb479b2a03bface/source/js/docs.js#L8027

This has proven to have many advantages in the specific use case of Cryptee, like if you've dropped an image, we can immediately embed the image into a cryptee document for example. 

Secondly, with things like photos (or gifs, and theoretically videos too), things get even more complicated. With unencrypted services, you can crop/resize/convert/ generate thumbnails on the server. With Cryptee, since everything is encrypted on your device, all this crop/resize/convert has to happen on your device, using the browser canvas. 

So because of the on-device encryption, when you upload a new photo, Cryptee first reads your original sized (O) photo encoded as base64, then uses the browser canvas to create :

1 – a cropped, small thumbnail for the gallery (SM), (which gets resized, cropped & compressed)
2 – a medium sized preview image for the lightbox preview image (M).  (which gets resized & compressed)
Then SM, M, and the original image (O) are all encrypted and uploaded.

https://github.com/cryptee/web-client/blob/42137a87de5d3725986f74f9beb479b2a03bface/source/js/photos.js#L3316-L3320

https://github.com/cryptee/web-client/blob/42137a87de5d3725986f74f9beb479b2a03bface/source/js/photos.js#L3414

–– and it becomes even more crucial with photos that things are stored Base64, and compressed & optimized, because with unencrypted services, you simply point your browser to an image file, let's say like : `<img src="photo.jpg"/>` then your browser does all the memory management, downloads the image, displays the image etc. 

Whereas with Cryptee, since everything is encrypted on your device, and all data on the server is encrypted, you can't simply point your browser to a url of an image. You first have to download images, decrypt, then inject it into the img tags as base64 for it to be displayed. 

This situation is insanely time-sensitive in order to keep the scroll smooth, so you can't do a lot of computation while scrolling. So decryption of each thumbnail gets distributed across multiple web-workers, as many threads as possible, then once decrypted, Cryptee puts these b64 into the image tags ahead of your browser's viewport. So if you have a fast internet connection, as you scroll, you don't even notice the download & decryption process. 

And memory management becomes incredibly complicated and important with 50+ photos. (some users have 10,000+ photos in some albums btw) – since you can't keep adding base64 into DOM, so you have to recycle DOM elements & virtualize the DOM, calculate the height of all images that are out of viewport, remove them all, then add them back in before they come back into viewport etc)

As much as I want to go into even deeper detail here, I can write a whole book about this topic, so I'll keep it brief. 

Long story short, depending on the type of file you upload, due to binary -> UTF8, Base64 encoding, compression, encryption – file sizes increase, and total memory use increases exponentially with the file size at various different stages of the process. So depending on the filetype, the content being serialized/encoded/encrypted you get unwanted side-effects like high-memory usage. 

Once Streams API becomes widely available, 99% of these problems will be gone. (except for cropping images, optimization, compression etc of course) Then we'll be able to simplify things immensely, and won't have to do all these steps.

Hoping this makes sense, and forgive me for cutting this short (!) 😅

P.S. – I've added this topic to our week's to-do list, and we'll check it one more time juuust in case, but if that's okay with you too, I'll close this issue since from the looks of it this is a device running out of memory issue, vs a code issue. (And of course if we find anything on our part I'll keep this thread updated) ✌🏻

**Comment by johnozbay** [comment] 2020-04-26 05:08
One more quick addition to my technical explanation earlier. 
Memory usage also heavily depends on how optimized OpenPGPjs is (and how well it performs on your device), since we use that for encryption / decryption.

[From the release changelog of OpenPGPjs 5 days ago](https://github.com/openpgpjs/openpgpjs/releases/tag/v4.10.3) : 
> Support compressed data packets with algorithm=uncompressed
> Fix memory usage when non-streaming-en/decrypting large files (broken in v4.10.2)

Linked just to show how complex of a process this is, and how many things have to work perfectly in harmony for in-browser encryption to happen as quickly & memory efficiently as intended. (otherwise we're not using 4.10.2, so this is unrelated) 😅

I think given the current state of browser APIs, it's an amazing miracle what the folks over at proton are achieving with OpenPGPjs – massive kudos to them for making all this goodness possible. [big fanboy here]

**Closed as completed** 2020-04-26 20:27 UTC
Labels: bug
