### ISSUE TITLE
cryptee should work completely without google

### ISSUE THREAD

**Issue by macandchief** [cryptee/web-client#42] opened 2020-02-29 23:49 UTC
If a service describes itself as "privacy focused", I would think it uses it's own secure infrastructure and certainly does not require something like a contact to a google server in order to log-in.

Unfortunately there is a connection to google necessary, if someone tries to use cryptee. It just makes no sense to me, how "privacy  focused" and the biggest data collecting company in history go together. It would be nice if this service was offered completely without google.

As a sidenote "privacy focused" and being on github do not match either.

**Comment by johnozbay** [comment] 2020-03-01 07:37
Hi there! 

We do use our own infrastructure.
Please take a look at #29, where I wrote about our specific use of Google in a _lengthy_ write-up, and feel free to reach out via our helpdesk if you have any additional questions. 

Closing this issue, because it's an identical duplicate of #29, where I wrote a _very lengthy_ answer addressing your exact concern, and your post contains neither an additional question, nor a feature suggestion.

P.S. regarding GitHub. – We used to have a self-hosted git repo, people have rightfully complained that we could change our commit history, and it's overall bad practice in security industry. We moved to GitLab, and people complained that it's not easy to find / navigate / use = thus they rightfully complained that it would draw less eyes on the code. There's no one-size fits all solution to this problem, and for now GitHub is the ideal one that works best at scale.

**Closed as completed by johnozbay** 2020-03-01 07:37 UTC
Labels: duplicate / already exists
