### ISSUE TITLE
[Bug] List elements in photos UI are occasionally duplicated

### ISSUE THREAD

**Issue by fschrofner** [cryptee/web-client#194] opened 2023-05-07 13:30 UTC
**Describe the bug**
A lot of times when I open photos on my phone or on my PC (both Firefox), all of my galleries appear twice.
So after scrolling through the list of galleries, it basically starts from the beginning and the list repeats itself.
Once it also happened for photos inside a gallery, but there the duplicates were right next to the original instead of repeating at the end of the list. 
Also, when I tried to select the duplicate photo (trying to remove it), it selected the first appearance, so it seems to be referring to the same instance of the photo.

**To Reproduce**
It happens quite often for me, when I simply open the photos on crypt.ee.
It might be happening more often, when I instantly scroll down on my phone while the photos/thumbnails are still decrypting (so list elements are shown, but thumbnails are not visible yet).

**Expected behavior**
Each gallery & photo should only appear once.

**System Information:**
_Phone_
 - Device: Fairphone 4
 - OS: Android 12
 - Browser: Firefox
 - Browser Version: 112.2.0
 - Browser Extensions: uBlock Origin

_Laptop_
 - Device: Lenovo ThinkPad Carbon X1 (Gen 9)
 - OS: OpenSUSE Tumbleweed
 - Browser: Firefox
 - Browser Version: 112.0.2
 - Browser Extensions: uBlock Origin

**Screenshots/Videos**
If it helps, I can provide videos of the behavior through a more private channel.

**Comment by johnozbay** [comment] 2023-06-21 05:32
Hi there! 

Thanks a lot for filing this @fschrofner! 🙏🏻 (I know that at some point @pabloscloud also filed this bug, and some of our users reached out to our helpdesk with more detailed breakdowns and screenshots) 

We've been hard at work, and I wanted to make sure we fix some of the underlying issues that may be causing this before addressing this bug individually. 

I can confirm that this is now fixed this in the alpha version and the issue is linked to our internal issue/release tracker.
Once the update with this fix is out (should be soon, we have to bundle this with another update that fixes other underlying issues), this issue will be closed automatically, and you'll get a notification!

Thank you so much for filing this, your help and patience! I know it took us a while to get back to this, but for a very good reason I promise. 

---
Some background info : this bug is actually the result of Cryptee doing what it's supposed to do, and gracefully failing without complaining about another underlying issue 😅 An issue which we've accidentally created while making some major remodeling of our APIs under the hood. 

A short summary is; the app doesn't confirm it received the albums / photos etc, despite having received them. So then at some point, a few ms later it makes another request, and only then, on the second try it confirms having received them. 

It may sound super silly, but it has to do with a bunch of other things like how the app checks if it started online but lost internet connectivity mid-way right away or if it started offline (but got connection later on), or one API request worked, but another failed etc etc. We've made some improvements to how we handle authentication / startup etc under bad network conditions, and accidentally caused this double display problem as a consequence. 

It doesn't mean the data is duplicated or anything, or there's no data loss or anything remotely serious like that. It just means the stuff is displayed twice on the screen thinking "oh wait did we load that? Were we connected when we did tho? Lemme do it again juuuuust in case". 

Hoping this makes sense 😅

I know it's super annoying, and we'll have a fix out for this as soon as humanly possible. Stay tuned!

**Comment by johnozbay** [comment] 2023-06-21 08:17
— btw oh hi @pabloscloud! I thought you deleted your account when I couldn't see your bug report, and when I clicked on your profile I got a 404. Happy to see you're still around 🙏🏻 ( I'm guessing you took your profile private. More power to you and so happy for you if that's the case! Didn't know it was possible for one to keep their github private, and learned something new today 😅 )

**Comment by pablo03v** [comment] 2023-06-21 10:23
No, must have been a bug. Couldn't find my issue in the app either but needed to visit the website. Very weird!! Thanks for your kind reply as always 💙

**Comment by pablo03v** [comment] 2023-06-26 16:12
I created a ticket regarding this GitHub issue I am experiencing

<img width="964" alt="Screenshot 2023-06-26 at 18 12 49" src="https://github.com/cryptee/web-client/assets/93644977/df32a36f-e65c-4271-bfc0-1c3edcfb86d2">

**Closed as completed** 2023-09-10 17:28 UTC
Labels: bug

**Comment by johnozbay** [comment] 2023-09-10 17:31
Hi there 👋🏻

This is now fixed and the fix is live! Let us know if you continue to experience this issue and we'll get it fixed much faster now that we know what's causing it. 

Thank you so much for filing this, your help and patience!

Best,

J
