### ISSUE TITLE
can't sign in on iOS

### ISSUE THREAD

**Issue by changemenemo** [cryptee/web-client#44] opened 2020-03-11 23:16 UTC
**Describe the bug**
try to sign in on ios platform after having installed the app as described on the website but it tells me that there is an error when I try to sign in. 

**Expected behavior**
should be able to signe in and have the screen with the encryption key
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iphone 11 and iphone XR
 - OS: [e.g. iOS8.1] iOS 13.3.1
 - Browser [e.g. stock browser, safari] safari and app installed

**Comment by changemenemo** [comment] 2020-03-11 23:22
![signal-2020-03-12-002015](https://user-images.githubusercontent.com/9523075/76473007-8228b800-63f7-11ea-96cc-1d221dfe03ae.jpeg)

Here are a screenshots of what happens... Maybe a problem with the password length or the kind of characters in it?

**Comment by johnozbay** [comment] 2020-03-12 10:54
Hi there! ✌🏻

I'm sorry to hear that you're having issues logging in.

We have thousands and thousands of users on iOS devices of all versions signing in/up, and using the service daily, so I don't think this is a service-wide bug / issue. 

If possible could you please reach out to our [helpdesk](https://crypt.ee/help) so that someone from the support team or myself can take a look to see if there's an issue with your account? 

There's about 100 anomaly alerts / indicators / signals that Cryptee watches out for to protect user safety. (These are all non-invasive non-tracker based things like how often an account types a password wrong, or sudden and repetitive IP-changes, flooding the APIs with abnormal numbers of requests, some requests going through as expected but some failing etc.) Rarely, these could be caused by content/ad blockers, corporate internet access points, poor internet connection, VPNs changing exit IP addresses, or a beta/yet-to-be-released version of a browser malfunctioning etc. (Often this happens with Firefox Betas on Linux or Chrome Betas on Chrome OS) – and all these / or a combination could result in getting your account / device flagged for your own security. So helpdesk can assist you so much more in situations like these. 

The most common reason why users experience issues like this on Cryptee has to do with content / ad blockers or browser extensions. As you can guess, most of Cryptee's users are very privacy sensitive, and have at least 4 - 5 blockers / extensions, or many custom Firefox privacy settings enabled, and sometimes these can break things, or mistakenly block Cryptee. So if you have any extensions, and wouldn't mind giving things another try with the blockers / extensions disabled (or using another browser), it would help us immensely while trying to identify the cause of the problem. 

I'll close this issue for now, because as far as I can we don't have a service wide issue, and. this is most likely an account-specific issue, so we'll be looking forward to your helpdesk ticket to solve this for you. 

I hope this makes sense,

All the best,
J

**Closed as completed by johnozbay** 2020-03-12 10:54 UTC
