### ISSUE TITLE
[Feature Request] Possibility to share content via a link

### ISSUE THREAD

**Issue by pablo03v** [cryptee/web-client#175] opened 2022-10-27 09:27 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a photo in my library that I want to share.

**Describe the solution you'd like**
A link that would lead to a photo/video(/document) so it will decrypt and show it on the website maybe with a description and metadata like time. (Could be protected with a password for privacy?)

**Additional context**
I would like to create a photo album (a real book) where I could print qrcodes with the link to a video cause I can't print an image and don't want to rely on unencrypted software like iCloud.

**Comment by johnozbay** [comment] 2022-10-27 09:29
Hi there! 
Thanks for filing this, but I'm afraid this is a duplicate of #122. 
Closing this so we can continue the conversation there. 
Best,
J

**Closed as completed by johnozbay** 2022-10-27 09:29 UTC
Labels: duplicate / already exists, feature request

**Comment by pablo03v** [comment] 2022-10-27 09:30
Sry I only searched for open issues :/

**Comment by johnozbay** [comment] 2022-10-27 09:32
No worries at all ✌🏻 
Thanks for understanding!

**Comment by pablo03v** [comment] 2022-10-27 09:34
And thanks for answering instantly :-)
