### ISSUE TITLE
Asking for Refund

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#195] opened 2023-05-25 11:49 UTC
I have been trying to contact the Cryptee support team for over a week now and I haven't gotten any reply.

I sent an email to info@crypt.ee, sent 2 or so messages on the online help portal at https://crypt.ee/help, I event sent an email to @johnozbay as I hadn't gotten a reply or even a notification acknowledging that my cries for help have even been received by someone, anyone!

I have overspent on my account by FAR too much (I had gotten the biggest plan), and I need that money back.

Running out of places to ask at this point, I even made this Github account to see if I could at least get some acknowledgement for what's happening!

So I throw this line out, and hope someone at this company or whatever bites, and I can finally get this resolved.

I heard that this company thing has their own 'zendesk-esque' help support system, and I have nothing good to say about it.

Hopefully I can finally get a reply! And maybe even my money that I need back!

**Comment by pablo03v** [comment] 2023-05-25 12:11
I don't think it has to do with the support system. I just guess they are very busy with the 3 new things on the horizon. I'm not saying that this is the correct behavior, but John has always been very active and answered every request of mine with competence (just look through my issues on here).

He also answered all my emails (tho a bit delayed tbh) with no questions left.

I'm almost certain he'll reply here or to the other channels were you sent your messages.

**Comment by johnozbay** [comment] 2023-05-25 12:11
Hi there! 

I can only imagine how frustrated you must be right now. Apologies for the time it's taking our support team to get back to you. But this isn't the correct place to address this issue. Nor is sending redundant emails / messages the right way to get help quicker. 

Our [terms and conditions clearly state that, since you can try all the features for free, we don't offer refunds](https://crypt.ee/terms#:~:text=since%20you%20are%20able%20to%20try%20out%20and%20use%20all%20features%20of%20the%20service%20for%20free%2C%20we%20do%20not%20offer%20refunds.). We had to come up with this policy due to the large number of payment fraud that takes place nowadays. Anything from users attempting to launder stolen cards via our service all the way to asking for refunds then trying to profit from currency exchange differences and fluctuations at time of refund, or uploading files for 29 days, deleting on 29th day, asking for refund, then uploading again to free-ride etc etc. I'm not a big fan of this policy but the alternative was unsustainable so we had to. And after-all, you can try all the features for free, and nobody forced you to pay for something you didn't need. (i.e. if you didn't need storage, or needed less storage, you could always start small and upgrade for larger storage plans later etc, we can't know what you need, hence the options)

If you've already reached out to our support team with your case, and why the team should make an exception for your refund, either a team member or myself will get back to you once we get to your case. I don't know the specifics of your case, and that's why I'm writing this generic response, so my apologies if all this sounds tone deaf. I'm merely writing this in response to this particular message.  

As for the speed, please be patient, as we are a small company, have very limited resources, dealing with rapid growth and have waaay too many users to interact with and help. While I know it's frustrating to wait to get a response from helpdesk, please bear in mind that you are not the only person we're responding to, and unlike large companies, for your own security, we don't have large customer support teams operating off-shore. Our teams operate here in Europe, bound by European labor laws, so they don't work overtime or late hours either to cover more shifts. 

> I heard that this company thing has their own 'zendesk-esque' help support system, and I have nothing good to say about it.

We do, and this is for your own security, so that third party companies like Zendesk based out of US can't get access to your data. The speed at which you're getting a response has nothing to do with the software we're using to manage our support tickets. It has to do with how busy our team is and tickets are prioritized. 

Closing this issue, because it's not a bug nor something that affects all users. 
Either myself or someone from our team will get back to you as soon as your ticket is next in line, and I'm sure that if you wrote the reasons for which you should be refunded, our team will process your refund immediately. 

Thanks for your understanding,

J

**Closed as completed** 2023-05-25 12:11 UTC
Labels: unrelated

**Comment by johnozbay** [comment] 2023-05-25 12:28
— Also thank you @pabloscloud for jumping so quickly to help a fellow community member 🙏🏻 Appreciate the kind response!

**Comment by johnozbay** [comment] 2023-05-27 15:39
Leaving this here for posterity in case if anyone stumbles upon this and wonders why our support team took so long to get back to the user who opened this issue (and deleted their github user immediately after opening this issue) 

I asked our support team what happened and found out that our payment processor Stripe flagged their payment as extremely high-risk, and gave it a high percentage score that it was likely made with a stolen or fraudulent credit card or a flagged pre-paid card etc. 

( _That said with larger amounts / plans, some banks and countries' cards are automatically flagged as 'elevated-risk' in our system, and if Stripe has a suspicion that something may be off, they're flagged as high risk or extremely high risk to save everyone headaches._ )

So our support team did exactly what they were supposed to do, and started investigating further to figure out if the payment could be fraudulent or not. (Especially considering that the user subscribed to the largest €320+ yearly plan immediately after signing up, but haven't uploaded a single file, and asked for a refund on that card. _which is what caused our support to react cautiously and take their sweet time to investigate_)

Once the investigation is over, we will resolve the issue with the help of Stripe's fraud-prevention team, and refund the amounts of the actual owner of the card (either the user who opened this thread, or the actual owner of the card if it indeed turns out to be a fraud) 

---

Until then, moral of the story,  — don't do payment fraud kids.
