### ISSUE TITLE
[Bug] Page flies away when selecting multiple files in a folder

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#71] opened 2020-06-11 01:48 UTC
**Describe the bug**
When selecting multiple files in the folder panel, sometimes either checking or unchecking the file will cause the entire page to fly vertically up and get stuck there. It seems non-deterministic but it happens very repeatably given enough selects or unselects.

**To Reproduce**
1. Create a number of files in a folder
2. Start checking files by clicking on their icon
3. Keep checking and unchecking until the page flies away
4a. After the page flies away, scrolling (tap and drag) can reset it to the right position.
4b. OR–Continuing to check and uncheck files will also eventually cause the page to return to its original position.

**Expected behavior**
Files get selected and the page stays attached to the screen.

**Screenshots**
![Image](https://user-images.githubusercontent.com/273696/84335691-47dfcb80-ab4a-11ea-95a0-8cb61826b2e6.gif)

**System Information:**
 - Device: iPhone 6s
 - OS: iOS 13.4.1
 - Browser Safari–PWA installed to home screen

**Comment by johnozbay** [comment] 2020-06-11 07:55
Hey there! 
Wow that's a strange layout bug! 😩
Thank you for filing this! 

– Bad news is that this seems like a safari-related layout bug.
– Good news is that it seems to be fixed after iOS 13.5.1. 
I've tested intensely with both 13.5.1 and 13.6 beta, and I can't seem to reproduce this in either one of the newer versions.

If possible, once you update to the latest iOS 13.5.1, if you wouldn't mind, could you try again and see if you can reproduce this? I don't have a 13.4.1 device handy – so I can't test my theory to confirm this.

Many million thanks 🙏🏻

**Comment by dhda** [comment] 2020-06-13 09:56
Good to hear that it’s fixed in later iOS versions. 13.4.1 is the last iOS version without the contact tracing API and I’m planning on staying on this version until I can evaluate that more. I’ll definitely come back around to this if/when I update!

**Comment by johnozbay** [comment] 2021-02-21 18:03
Today's version 3.0 release a complete re-write of the application, and fixes this in 01edfe4! 

Many thanks for filing this! ✌🏻  Closing this now, but needless to say please let me know if you run into similar issues with the new version!

**Closed as completed by johnozbay** 2021-02-21 18:03 UTC
Labels: bug
