### ISSUE TITLE
[Feature Request] Add word count and date support for other languages.

### ISSUE THREAD

**Issue by LinYuyang86** [cryptee/web-client#203] opened 2024-01-07 03:20 UTC
Can your team provide word count support for other languages in the docs ? Languages like Japanese and Chinese.
People in Asian countries very need it.
For that,your team can put this feature in settings-app preferences-cryptee docs preferences.It is up to the user to choose whether to enable it.

**Comment by johnozbay** [comment] 2024-05-15 11:11
Hi there 👋🏻

Apologies for the delayed response on this, we've been working on our text editor's core, and took us a while to fix a bunch of other things until we can get to this. 

We have now fixed this in the upcoming release, and you can expect our word count to work correctly depending on your browser and operating system's built in language settings. For example, if your browser / operating system uses Japanese, this : 

```
吾輩は猫である。名前はたぬき。
```
Would be counted as **1 word** in our _old version_.

_Our new version_ will recognize it as **8 words** : 
```
'吾輩'
'は'
'猫'
'で'
'ある'
'。'
'名前'
'は'
'たぬき'
'。'
```

Please note that this will work only if the operating system / browser detects the language correctly for the text that is on the screen. We discovered that there are a few scenarios where this could fail. say for example if the first paragraph in your text is in English, but the rest is Japanese etc, then the browser / os might think it's supposed to recognize English etc. 

--- 

This is now fixed this in the alpha version and the issue is linked to our internal issue/release tracker.
Once the update with this fix is out (should be in a few days), this issue will be closed automatically, and you'll get a notification. 

Once it's out, give it a try, and let us know if it's working as expected or not. We would be happy to make adjustments to get this right. 
 
Thank you so much for filing this, your help and patience!
I'm sorry it took us so long to fix this and accommodate more languages. 


Best,

J

**Closed as completed** 2024-05-17 18:03 UTC
Labels: bug, feature request
