### ISSUE TITLE
[Bug] Firefox Exported ECD uses JSON Extension

### ISSUE THREAD

**Issue by jebbster88** [cryptee/web-client#114] opened 2021-03-08 16:58 UTC
As per comments in another issue. Downloading as ECD from firefox consistently results in a .json download, chrome however results in a .ecd

Will follow up with more info when I have it.

--------
@jebbster88 It's super strange that your export resulted in a JSON format – that sounds like a whole separate bug right there. 

ECD uses a json structure on the inside, but your file should have been something like   `file.ecd`  (Encrypted Cryptee Document)    or  `file.uecd` (Unencrypted Cryptee Document) 

I wonder if this happens because your browser ignores the save-as name, (which ends with .ecd) and instead tries to sniff the filetype from the mime-type. ECD uses `application/json` – so this could be a strange separate bug. If possible could you please try this out and if you can reproduce what caused the filename issue file a separate issue for this ?

_Originally posted by @johnozbay in https://github.com/cryptee/web-client/issues/102#issuecomment-792727965_

**Comment by jebbster88** [comment] 2021-03-08 17:25
Almost certainly related to below. So most likely not a cryptee issue.

https://github.com/eligrey/FileSaver.js/issues/314
https://bugzilla.mozilla.org/show_bug.cgi?id=1684183

**Comment by johnozbay** [comment] 2021-03-08 18:23
Wow! Amazing discovery!
That's just next level weird.

I don't know why on earth Mozilla would casually decide to replace filenames / extensions of downloads 🤦🏻‍♂️
At least they seem to be on the right track now. 
https://hg.mozilla.org/integration/autoland/rev/181e16e12d9d

Thanks a lot for filing this here! 
Deeply appreciate it! We'll keep an eye out on this and try to solve this right away! (or at least find a temp workaround)

**Comment by johnozbay** [comment] 2022-03-02 11:07
Some good news! Revisiting this – it seems to be fixed now. Closing 🎉
Many million thanks for spotting this bug, filing this issue, and digging up the root cause! 
Deeply appreciate the help! ✌🏻
Best,
J

**Closed as completed by johnozbay** 2022-03-02 11:07 UTC
Labels: bug, depends on 3rd party / unrelated
