### ISSUE TITLE
[Bug] Issues with Justified Text 

### ISSUE THREAD

**Issue by koch17** [cryptee/web-client#47] opened 2020-03-22 02:34 UTC
When in justify mode, the space between the words disappears once you start typing. This problem is unique to justify mode only. Please check the short gif to reproduce.
Thank you for this excellent service.

![crypt](https://user-images.githubusercontent.com/50534491/77241057-aa68a180-6bc3-11ea-83a9-aed9b5f3d8fc.gif)

**Comment by johnozbay** [comment] 2020-03-22 09:15
Hi there! 

Thank you so much for reaching out with this, and for your kind words! 
Glad to hear you're enjoying the service despite these silly bugs I've missed. 

If possible could you please let me know which OS & browser are you seeing this in? So that I can create a better, specific and future-proof test-case. 

I can confirm that I can reproduce this in Firefox on OS X.

But it seems to be working as expected in OS X Chromium:

![image](https://user-images.githubusercontent.com/611338/77246207-95c0f380-6c2d-11ea-8fda-c7f6118419a4.png)

And in OS X Safari: 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/611338/77246224-d456ae00-6c2d-11ea-82c2-e54ab234ff00.png">

I will find out what's causing this and release a fix for this in the next 24 - 48 hours.
Thank you for your help, kindness, understanding and patience! 🙏🏻 
Deeply appreciated!

**Comment by koch17** [comment] 2020-03-22 15:04
Hi, 
Sorry for incomplete information. It looks like this is a firefox specific problem, I have two laptops running on windows and linux and this bug exists on each of them. On windows I have tried brave browser too and this bug doesn't exist there.
Best

**Closed as completed** 2020-03-24 21:28 UTC
Labels: bug

**Comment by johnozbay** [comment] 2020-03-24 21:35
No worries at all! I can confirm that we've fixed this bug in today's release! 
Feel free to let me know if you run into anything like this again! ✌🏻
Many thanks for catching this! 

Apologies that it ended up being a 48 hour-fix, and not 24. 

We've been re-factoring the entire app in preparation for today's release. The app is now 45% smaller, so we had to verify this against a ton of other changes. 🎉

**Comment by koch17** [comment] 2020-03-24 23:26
Thank you very much for such a quick fix and no worries about it taking longer, even if it took a week or two, it would be fine with me. I see how much energy you put into this. I will let you know of any bugs I find or any improvements I think the project will benefit from.
